### ISSUE TITLE
No module named 'vnpy_ctptest.api.vnctpmd

### ISSUE THREAD

**Issue by enjlife** [vnpy/vnpy_ctptest#11]
mac下pip安装后，报以上错误。
Traceback (most recent call last):
  File "/Users/enjlife/git/vnpy/examples/test.py", line 4, in <module>
    import vnpy_ctptest
  File "/Users/enjlife/anaconda3/envs/py310/lib/python3.10/site-packages/vnpy_ctptest/__init__.py", line 25, in <module>
    from .gateway import CtptestGateway
  File "/Users/enjlife/anaconda3/envs/py310/lib/python3.10/site-packages/vnpy_ctptest/gateway/__init__.py", line 1, in <module>
    from .ctptest_gateway import CtptestGateway
  File "/Users/enjlife/anaconda3/envs/py310/lib/python3.10/site-packages/vnpy_ctptest/gateway/ctptest_gateway.py", line 32, in <module>
    from ..api import (
  File "/Users/enjlife/anaconda3/envs/py310/lib/python3.10/site-packages/vnpy_ctptest/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ModuleNotFoundError: No module named 'vnpy_ctptest.api.vnctpmd'

**Comment by vnpy** [comment]
vnpy_ctptest没有支持Mac系统，穿透式测试请使用Windows了

**Comment by enjlife** [comment]
> vnpy_ctptest没有支持Mac系统，穿透式测试请使用Windows了

好的，谢谢。
